---
- name: "Creates backend app directory"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Unarchive backend files"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i


- name: "Executing Node app with PM2"
  shell: |
    cd /home/ubuntu/backend
    pwd
    export TYPEORM_CONNECTION="postgres"
    export TYPEORM_MIGRATIONS_DIR="./migrations"
    export TYPEORM_MIGRATIONS="./migrations/*.js"
    export TYPEORM_ENTITIES="./modules/domain/**/*.entity.js"
    export TYPEORM_HOST="postgres.cbsvnr80nf1o.us-east-1.rds.amazonaws.com"
    export TYPEORM_PORT="5432"
    export TYPEORM_USERNAME="postgres"
    export TYPEORM_PASSWORD="12345678"
    export TYPEORM_DATABASE="postgres"
    pm2 stop default
    pm2 start main.js